### PR TITLE
Fix bug with spaces in hubsupport search

### LINKED ISSUE #110: `/hubsupport` search fails when the search term contains a space
Searching `plank` correctly finds [the Plank Sack hub plugin](https://runelite.net/plugin-hub/show/plank-sack), however searching `plank s` (or any other substring) comes back with no results.

### PR DESCRIPTION
**Pull request by JamesJJT**
Fixes #110 

Replacing spaces with dashes fixes #110 as the `internalName` from `https://repo.runelite.net/plugins/manifest/${version}_full.js` seems to return spaces as dashes. 

Example test.

Input = `plank sack`

Pre fix: 

image

Post fix:
image

### CODE REVIEW

**Review by Nightfirecat — APPROVED** [review]

File: lib/commands/hubsupport.js [hunk 1]
```diff
@@ -34,7 +34,9 @@ export default {
       .setAutocomplete(true)
     ),
   async execute (interaction) {
-    const value = interaction.options.getString('name')
+    let value = interaction.options.getString('name')
+    // Replace spaces with dashes to fix an issue with spaces not returning anything
+    value = value.replace(/\s+/g, '-')
```
Comment (deathbeam) [inline lib/commands/hubsupport.js:39]: this should go below the check where it checks if value is empty or not

**Review by deathbeam — CHANGES_REQUESTED** [review]

**Comment by JamesJJT** [comment]
@deathbeam done

**Review by deathbeam — APPROVED** [review]
